### ISSUE TITLE
Reference Mpv.NET for prerequisites and licensing

### ISSUE THREAD

**Issue by hudec117** [mysteryx93/MediaPlayerUI.NET#1]
I have updated the [prerequisites](https://github.com/hudec117/Mpv.NET#prerequisites) and [licensing](https://github.com/hudec117/Mpv.NET#licensing) section in Mpv.NET. To reduce the need of updating these 2 sections in your project, could you please reference/link to the Mpv.NET project instead?

**Comment by mysteryx93** [comment]
done
