### ISSUE TITLE
Can you make your repo to target .NET 5.0?

### ISSUE THREAD

**Issue by zydjohnHotmail** [mysteryx93/MediaPlayerUI.NET#2]
Hello:
I found your repo, it seems to be interesting.  I tried to create one C# WinForms project for targetting .NET 5.0 and install nuget package, but I can see the warning in the reference.
Warning	NU1701	Package 'MediaPlayerUI.NET 0.9.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.
Since your repo is not in version 1.0 yet, is it possible that you can make to target .NET 5.0 or even .NET 6.0, which is coming in a few months.
You know that not many people will still use old .NETFramework version, if Microsoft is doing something different.
I am using Windows 10 (Version 21H1) and Visual Studio 2019 Version 16.10.4.
Thanks,

**Comment by mysteryx93** [comment]
I'll update it when I'm back. I think I got uncommitted changes to that project.

**Comment by mysteryx93** [comment]
I'm refactoring the project to add support other than WPF.

MediaPlayer.WPF.Mpv now targets .NET Core 3.1

It's not yet published on NuGet. Take it from the repository and let me know if you encounter issues to fix.

**Comment by zydjohnHotmail** [comment]
Hello:
As .NET 6.0 is already GA.  I tried to create one C# WinForms project for targetting .NET 6.0 and install nuget package, but I can see the warning in the reference.
Warning NU1701 Package 'MediaPlayerUI.NET 0.9.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.
I want to know if you have some time to upgrade the repo to target .NET 6.0, (6.0 is long time support), I also need to use the repo in WinForms app, not in WPF.
Thanks,

**Comment by mysteryx93** [comment]
The refactoring is done but not released as NuGet yet. You can clone my Git and use that version, and let me know if you encounter any issue.

**Comment by zydjohnHotmail** [comment]
Hello:
Let me know when you will release in NuGet.
Thanks,

**Comment by mysteryx93** [comment]
It's now released
https://www.nuget.org/packages/MediaPlayer.Wpf.Mpv/

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your work.  But I want to see some code sample on how to use the repo. in WinForms App.
Thanks,

**Comment by mysteryx93** [comment]
This project supports WPF and Avalonia, not WinForms.
