### ISSUE TITLE
How to switch the video source？

### ISSUE THREAD

**Issue by forcharlotte** [mysteryx93/MediaPlayerUI.NET#6]
How to switch the video source, I tried to use MVVM or modify the Source directly, but could not switch the video

**Comment by forcharlotte** [comment]
public class PlayerWindowViewModel : BindableBase
    {
        private string _mpvSource = "D:\\video1.mp4";
        public string MpvSource
        {
            get { return _mpvSource; }
            set { SetProperty(ref _mpvSource, value); }
        }

        private readonly IEventAggregator _eventAggregator;
        public PlayerWindowViewModel(IEventAggregator eventAggregator)
        {
            _eventAggregator = eventAggregator;
            _eventAggregator.GetEvent<VideoChangeEvent>().Subscribe(ChageVideo);
        }

        private void ChageVideo(string obj)
        { 
            MpvSource = "D:\\video2.mp4"; ;
        }
    }
In the WPF MPV application, I tried to switch sources using the above method, but there was no response

**Comment by mysteryx93** [comment]
You just set the Source property and bind to it. Not sure what you're doing with `IEventAggregator`

```c#
// With Fody.PropertyChanged, or implementing change notification manually
public string MpvSource { get; set; } = string.Empty;

private void ChageVideo(string obj)
{ 
    MpvSource = obj;
}
```

**Comment by forcharlotte** [comment]
IEventAggregator is the event notification for Prism, I tried to switch the video using the method you gave, but the video currently playing is not stopped and switched，I don't know what I got wrong. Here is my test program, I did not upload mpv-1.dll due to the upload file size limit
[VideoPlayerTest.zip](https://github.com/mysteryx93/MediaPlayerUI.NET/files/11394523/VideoPlayerTest.zip)
