### ISSUE TITLE
Does it support real-time microphone acquisition and output?

### ISSUE THREAD

**Issue by pyking-wang** [mysteryx93/MediaPlayerUI.NET#8]
[MediaPlayer.Avalonia.Bass]
I would like to know if it can achieve real-time microphone acquisition and output, rather than just playing MP3 files. 
Thank you.

**Comment by mysteryx93** [comment]
MediaPlayerUI is designed to be generic allowing for any custom implementation. One custom implementation I did was to preview VapourSynth video scripts.

With that in mind, you can create your own `MediaPlayerHost` for your needs.

BASS library is extremely flexible. As to whether it support your needs (which probably does, but there's a steep learning curve), look over to their website and community
https://www.un4seen.com
